travis:
  secure:
    BINSTAR_TOKEN: l1QutYSLpdVGxMsV49iARXSBHPBS17S66jGyThcp7qDotw+KVVOS4oB5I4zqoEMXLPK7xnbgGV2RGAYp90VGh6PuwaKgE9hDWTVbdPWqvNq6MSYLTTvW9f7iC7zfdx9DhNNIVmTQfI9S2WiD08uHpLD/YhA74dzkGwYRz0d79sxcZR5nu9R2dv1VHe/7Nw71Gclq/20VjV/XDo09QP76JK0M/aAEXyUkFw8cBJkMMikTyi6eUL7MlvvA1TdlTxN/sdZ7GTzJnM7wSA25Mqo8iTLOoeKgl7WkrZRWp9A0v2NRXqs5nldhYTdmqOB5XjUsZFq5eX681q2HDPqyVOSMJOEPSaYtEhP/TGwBepp3CzGW2PCy2EE2CEqRl670mSubPhxUWCh2ZpYXOxVWWWWx0h2hbqyHs9OQpPXqIw+PGBu/B9ugiiGe3PcG5X+yz2fT7en+qLZuX6AOPFHXNzUKnhm2DgIGJUq/6sOv59EEl52rFPY3oGBoajny4IcY1IulkIor+ObYs2K8CkasTZ8vXBx8aZykqC++7y1k5/0my7R9hXiz9fLG7x3SWBLpuhJsaHeI3HcdqaGUS3Ck4y+mMuN7Q49zjuvPTphkrDjIDC+kZ3PKFVt9IeAkRfhw13Y2k00oJ8jGVFq3EIr+IVyekwrMnkTgUoylUktxPV6aHow=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
